proxy:
  listen:
    address: "127.0.0.1"
    port: 80

  services:
    - name: my-service
      domain: my-service.my-company.com
      strategy: roundrobin
      hosts:
        - address: "scooterlabs.com/echo?foo1=bar1"
          port: 80
        - address: "scooterlabs.com/echo?foo2=bar2"
          port: 80
    - name: my-service2
      domain: my-service2.my-company.com
      strategy: random
      hosts:
        - address: "scooterlabs.com/echo?foo3=bar3"
          port: 80
        - address: "scooterlabs.com/echo?foo4=bar4"
          port: 80

  monitoring:
    address: "127.0.0.1"
    port: 8081